site_name: "ktsreference"
site_url: https://axelgard.github.io/mkdocs-demo/
site_author: AxelGard 
repo_name: axelgard/ktsreference
repo_url: https://github.com/AxelGard/ktsreference

markdown_extensions:
  - codehilite
  - pymdownx.highlight
  - pymdownx.superfences
theme:
  name: readthedocs